-- Run this in the Supabase SQL Editor to initialize or update the schema

-- 1. Create Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text,
  full_name text,
  avatar_url text,
  channel_id text not null,
  discord_guild_id text,
  ticket_id bigint, -- Set below as foreign key
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Knowledge Base Table
create table if not exists knowledge_base (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Teams Table
create table if not exists teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid references auth.users(id),
  discord_guild_id text,
  created_at timestamp with time zone default now()
);

-- 4. Create Profiles Table (for subscriptions and user data)
create table if not exists profiles (
  id uuid primary key references auth.users(id),
  email text,
  full_name text,
  avatar_url text,
  subscription_tier text default 'none',
  status text default 'pending_payment',
  discord_id text,
  discord_user_id text,
  discord_guild_id text,
  discord_status text,
  stripe_customer_id text,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  admin_id uuid,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create Tickets Table
create table if not exists tickets (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users(id),
  assignee_id uuid references auth.users(id),
  team_id uuid references teams(id),
  user_name text,
  discord_id text,
  discord_guild_id text,
  title text,
  description text,
  urgency_score int default 1,
  status text default 'open',
  type text default 'support',
  priority text default 'medium',
  location text default 'unknown',
  solution text,
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Add Foreign Keys
alter table messages drop constraint if exists messages_ticket_id_fkey;
alter table messages add constraint messages_ticket_id_fkey foreign key (ticket_id) references tickets(id);

-- 7. RLS Policies
alter table messages enable row level security;
alter table knowledge_base enable row level security;
alter table profiles enable row level security;
alter table teams enable row level security;
alter table tickets enable row level security;

-- (Policies truncated - add your specific RLS policies here)

-- 8. Auto-create Profile Trigger
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

