-- Run this in the Supabase SQL Editor

-- 1. Create Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text,
  channel_id text not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Knowledge Base Table
create table if not exists knowledge_base (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table messages enable row level security;
alter table knowledge_base enable row level security;

-- 4. Create Profiles Table (for subscriptions)
create table if not exists profiles (
  id uuid primary key references auth.users(id), -- Changed to uuid to match auth.users
  subscription_tier text,
  status text,
  discord_guild_id text,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

-- 5. Create Tickets Table
create table if not exists tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id), -- Changed to uuid to match auth.users
  user_name text,
  issue text,
  summary text,
  urgency int default 1,
  status text default 'OPEN', -- 'OPEN', 'CLOSED', 'RESOLVED'
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table tickets enable row level security;

-- 6. RLS Policies
drop policy if exists "Users can view their own tickets" on tickets;
create policy "Users can view their own tickets" 
  on tickets for select 
  using (auth.uid()::text = user_id::text);

drop policy if exists "Users can insert their own tickets" on tickets;
create policy "Users can insert their own tickets" 
  on tickets for insert 
  with check (auth.uid()::text = user_id::text);

drop policy if exists "Users can view their own profile" on profiles;
create policy "Users can view their own profile" 
  on profiles for select 
  using (auth.uid()::text = id::text);

drop policy if exists "Users can update their own profile" on profiles;
create policy "Users can update their own profile" 
  on profiles for update
  using (auth.uid()::text = id::text);

-- 7. Auto-create Profile Trigger
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, subscription_tier, status)
  values (new.id, 'none', 'pending_payment');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

