import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    print("Error: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not found in .env")
    exit(1)

supabase: Client = create_client(url, key)

sql = """
-- 1. FIX TEAM_MEMBERS RLS POLICIES
DROP POLICY IF EXISTS "Users can view team members of their teams" ON team_members;
DROP POLICY IF EXISTS "Team owners can manage members" ON team_members;
DROP POLICY IF EXISTS "Users can insert themselves into teams" ON team_members;

CREATE POLICY "Users can view team members of their teams"
ON team_members FOR SELECT
TO authenticated
USING (
  team_id IN (
    SELECT team_id 
    FROM team_members 
    WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Allow team member inserts"
ON team_members FOR INSERT
TO authenticated
WITH CHECK (
  team_id IN (
    SELECT id FROM teams WHERE owner_id = auth.uid()
  )
  OR
  user_id = auth.uid()
);

CREATE POLICY "Team owners can update members"
ON team_members FOR UPDATE
TO authenticated
USING (
  team_id IN (
    SELECT id FROM teams WHERE owner_id = auth.uid()
  )
);

CREATE POLICY "Team owners and users can delete members"
ON team_members FOR DELETE
TO authenticated
USING (
  team_id IN (
    SELECT id FROM teams WHERE owner_id = auth.uid()
  )
  OR
  user_id = auth.uid()
);

-- 2. CREATE AUDIT_LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGSERIAL PRIMARY KEY,
    actor_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to view audit logs" ON public.audit_logs;
CREATE POLICY "Allow authenticated users to view audit logs"
    ON public.audit_logs
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Only service role can insert audit logs" ON public.audit_logs;
CREATE POLICY "Only service role can insert audit logs"
    ON public.audit_logs
    FOR INSERT
    TO service_role
    WITH CHECK (true);

-- 3. CREATE NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notifications" ON notifications;
CREATE POLICY "Users can view their own notifications"
  ON notifications FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications"
  ON notifications FOR UPDATE
  USING (auth.uid() = user_id);

-- 4. CREATE NOTIFICATION TRIGGER
CREATE OR REPLACE FUNCTION public.handle_ticket_notification()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'UPDATE' AND OLD.assignee_id IS DISTINCT FROM NEW.assignee_id AND NEW.assignee_id IS NOT NULL) THEN
    INSERT INTO public.notifications (user_id, type, title, message, link)
    VALUES (NEW.assignee_id, 'assignment', 'New Ticket Assigned', 'You have been assigned to ticket #' || NEW.id, '/dashboard/tickets?id=' || NEW.id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_ticket_updated_notify ON tickets;
CREATE TRIGGER on_ticket_updated_notify
  AFTER UPDATE ON tickets
  FOR EACH ROW EXECUTE PROCEDURE public.handle_ticket_notification();
"""

try:
    # Use the rpc run_sql if available, or try executing directly if the client supports it
    # Note: supabase-py doesn't have a direct 'execute' method for arbitrary SQL easily available
    # but we can try calling the PostgREST extension if it's there, or just use the management API logic.
    # Actually, a better way for one-off SQL via python is usually via a database connection (psycopg2)
    # but I don't have the password.
    
    # Wait, I'll try to use the 'rpc' method if the user has a run_sql function, but they probably don't.
    # If the MCP failed, maybe I can just try to run it via curl to the management API if I had a token.
    
    # Since I don't have a direct SQL execution method without the DB password, 
    # and the MCP is EOF, I will try to use the python backend's existing infrastructure 
    # to see if it has a way to run migrations.
    
    print("Attempting to run SQL via Supabase RPC...")
    # This is a shot in the dark, but some projects have this helper
    res = supabase.rpc("run_sql", {"sql": sql}).execute()
    print("Result:", res)
except Exception as e:
    print("Error running SQL via RPC:", e)
    print("\nFalling back to suggesting manual execution since direct SQL execution is restricted to the SQL Editor in the Dashboard.")
