export const TEAM_ROLES = [
    "Admin",
    "Developer",
    "IT",
    "Software Developer",
    "Software Engineer",
    "Front-End Developer",
    "Back-End Developer",
    "Full-Stack Developer",
    "Web Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "Game Developer",
    "Embedded Systems Developer",
    "API Developer",
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Business Intelligence Developer",
    "Big Data Engineer",
    "Analytics Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Site Reliability Engineer",
    "Infrastructure Engineer",
    "Platform Engineer",
    "Systems Engineer",
    "Build and Release Engineer",
    "Cyber Security Analyst",
    "Security Engineer",
    "Penetration Tester",
    "SOC Analyst",
    "Information Security Officer",
    "Network Security Engineer",
    "Risk and Compliance Analyst",
    "Network Engineer",
    "Systems Administrator",
    "IT Administrator",
    "Database Administrator",
    "IT Operations Engineer",
    "Server Engineer",
    "Software Tester",
    "QA Analyst",
    "QA Engineer",
    "Test Automation Engineer",
    "Performance Tester",
    "UAT Tester",
    "UI Designer",
    "UX Designer",
    "Product Designer",
    "Interaction Designer",
    "Accessibility Specialist",
    "Product Manager",
    "Technical Product Manager",
    "Project Manager",
    "Scrum Master",
    "Agile Coach",
    "Business Analyst",
    "Systems Analyst",
    "IT Support Technician",
    "Service Desk Analyst",
    "Helpdesk Technician",
    "Application Support Analyst",
    "Desktop Support Engineer",
    "Software Architect",
    "Solutions Architect",
    "Enterprise Architect",
    "Technical Lead",
    "Engineering Manager",
    "Chief Technology Officer",
    "Head of IT"
];
